# Generated by Django 5.1.5 on 2025-05-19 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('newsletter', '0011_alter_article_id_alter_attachment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='newsletter.subscription')),
                ('localita_field', models.CharField(blank=True, db_column='localita', help_text='optional', max_length=30, null=True, verbose_name='localita')),
            ],
            bases=('newsletter.subscription',),
        ),
    ]
