# Generated by Django 2.2.11 on 2020-03-22 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogView', '0003_auto_20200322_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterregistration',
            name='data_registrazione',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='newsletterregistration',
            name='data_revoca',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsletterregistration',
            name='indirizzo_mail',
            field=models.EmailField(help_text='Inserisci lemail dove vuoi ricevere la newsletter', max_length=254, unique=True, verbose_name='Inserisci il tuo indirizzo di email'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
