# Generated by Django 5.1.5 on 2025-01-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogView', '0004_auto_20200322_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterregistration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
