# Generated by Django 5.1.5 on 2025-04-29 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gruppo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('creato_da', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Barista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('turni_effettuati', models.IntegerField(default=0)),
                ('gruppo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turni_bar.gruppo')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('barista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turni_bar.barista')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
