# Generated by Django 5.1.5 on 2025-10-01 20:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('situation', models.TextField(verbose_name='Situazione')),
                ('body_sensations', models.JSONField(default=list, verbose_name='Sensazioni corporee')),
                ('energy_type', models.CharField(blank=True, max_length=200, verbose_name='Tipo di energia')),
                ('triggers', models.JSONField(default=list, verbose_name='Fattori scatenanti')),
                ('impulses', models.JSONField(default=list, verbose_name="Impulsi all'azione")),
                ('intensity', models.IntegerField(default=5, verbose_name='Intensità (1-10)')),
                ('valence', models.CharField(blank=True, max_length=100, verbose_name='Valenza emotiva')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='Durata')),
                ('identified_emotions', models.JSONField(default=list, verbose_name='Emozioni identificate')),
                ('personal_notes', models.TextField(blank=True, verbose_name='Note personali')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_identifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Identificazione Emotiva',
                'verbose_name_plural': 'Identificazioni Emotive',
                'ordering': ['-created_at'],
            },
        ),
    ]
